### ISSUE TITLE
Bad argument type to SetConsoleTitleW on Window/Python35

### ISSUE THREAD

**Issue by radssh** [tartley/colorama#110]
Colorama 0.3.7 raises TypeError exception under Python3.5 when attempting to set window title via ANSI escape sequence.

```
>>> s
'\x1b]2;Foo\x07'
>>> print(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\colorama\ansitowin32.py", line 163, in write_and_convert
    text = self.convert_osc(text)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\colorama\ansitowin32.py", line 235, in convert_osc
    winterm.set_title(params[1])
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\colorama\winterm.py", line 162, in set_title
    win32.SetConsoleTitle(title)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\colorama\win32.py", line 154, in SetConsoleTitle
    return _SetConsoleTitleW(title)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

**Comment by wiggin15** [comment]
Thanks for reporting this! Can you please check if the latest code in this repository fixes your problem?

**Comment by radssh** [comment]
Test looks good with latest code. Thanks!

**Comment by radssh** [comment]
Any timetable for a versioned release with this fix?
