### ISSUE TITLE
set_title inside PyCharm

### ISSUE THREAD

**Issue by Viatorus** [tartley/colorama#118]
Running my code inside PyCharm 2016.1 (python 3.4, colorama 0.3.7, linux) I get this error for set_title:

````python
Traceback (most recent call last):
  File ".../run.py", line 7, in <module>
    print(ansi.set_title('My Title'))
  File ".../ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File ".../ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File ".../ansitowin32.py", line 163, in write_and_convert
    text = self.convert_osc(text)
  File ".../ansitowin32.py", line 235, in convert_osc
    winterm.set_title(params[1])
AttributeError: 'NoneType' object has no attribute 'set_title'
````

It happens right here:
````python
def convert_osc(self, text):
    for match in self.ANSI_OSC_RE.finditer(text):
        start, end = match.span()
        text = text[:start] + text[end:]
        paramstring, command = match.groups()
        if command in '\x07':       # \x07 = BEL
            params = paramstring.split(";")
            # 0 - change title and icon (we will only change title)
            # 1 - change icon (we don't support this)
            # 2 - change title
            if params[0] in '02':
                winterm.set_title(params[1]) #  <<< winterm is None
    return text
`````
It seems that colorama things I am on a windows machine?

**Comment by Viatorus** [comment]
On a windows device I get this error:

```javascript

Traceback (most recent call last):
  File "C:\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python35\lib\site-packages\****\__main__.py", line 3, in <module>
    main()
  File "C:\python35\lib\site-packages\****\main.py", line 32, in main
    ts.run()
  File "C:\python35\lib\site-packages\****\test.py", line 39, in run
    print(ansi.set_title('Foo'))
  File "C:\python35\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\python35\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\python35\lib\site-packages\colorama\ansitowin32.py", line 163, in write_and_convert
    text = self.convert_osc(text)
  File "C:\python35\lib\site-packages\colorama\ansitowin32.py", line 235, in convert_osc
    winterm.set_title(params[1])
  File "C:\python35\lib\site-packages\colorama\winterm.py", line 162, in set_title
    win32.SetConsoleTitle(title)
  File "C:\python35\lib\site-packages\colorama\win32.py", line 154, in SetConsoleTitle
    return _SetConsoleTitleW(title)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

```

**Comment by jakul** [comment]
I'm having the same error (though not through PyCharm). Did you work out why colorama thought you were on a Windows machine @Viatorus ?
