### ISSUE TITLE
pip-compile command fail with colorama under windows

### ISSUE THREAD

**Issue by M0dM** [tartley/colorama#152]
Hi,

I had trouble compiling my requirement file today.
The error seems comming from a colorama's problem under windows.

The error:
```bash
(dxf_authn) PS C:\Users\benoit.brayer\Svn\WebProducts\Dxf2Dxf\authn> pip-compile.exe .\requirements\reqs_test.in
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\benoit.brayer\.virtualenvs\dxf_authn\Scripts\pip-compile.exe\__main__.py", line 9, in <module>
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\piptools\scripts\compile.py", line 225, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\piptools\resolver.py", line 297, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\piptools\cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\piptools\cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\piptools\utils.py", line 200, in lookup_table
    for value in values:
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\piptools\cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\pkg_resources\__init__.py", line 3037, in parse
    req, = parse_requirements(s)
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\pkg_resources\__init__.py", line 2981, in parse_requirements
    "version spec")
  File "c:\users\benoit.brayer\.virtualenvs\dxf_authn\lib\site-packages\pkg_resources\__init__.py", line 2946, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in colorama; sys_platform == "win32" at ; sys_platform == "win32"
```

* I am using : Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
* I am using pew (https://github.com/berdario/pew) to manage my virtual envs under windows.

Attached zip file : [reqs_test.zip](https://github.com/tartley/colorama/files/1575212/reqs_test.zip)

Step to reproduce:
1. Copy attached file from zip everywhere on your harddrive
2. Setup pew (pip install pew) with powershell
3. Create new virtualenv called test (pew new test)
4. Setup pip-tools (pip install pip-tools)
5. Try to build the attached file using pip-compile (pip-compile reqs_test.in)

**Comment by wiggin15** [comment]
This doesn't look related to colorama, as this project has no dependencies. Google results suggest it may be an older version of pip. Please try running:
`pip install --upgrade setuptools pip`

**Comment by M0dM** [comment]
pip was already up to date.
setuptools update fixed the problem.

Thanks.
