### ISSUE TITLE
 Don't depend to ctypes on Linux

### ISSUE THREAD

**Issue by haypo** [tartley/colorama#18]
Hi,

On CPython buildbot "FreeBSD 7.2, the compilation of the ctypes module fails. The pip module cannot be used because it imports colorama which uses ctypes for its win32 module, and the win32 module is always imported, even on Linux. IMO it would be better to not import this module on Linux to avoid the dependency to ctypes.

I also reported the issue to pip:
https://github.com/pypa/pip/issues/2079

Test output on the buildbot:

======================================================================
FAIL: test_with_pip (test.test_venv.EnsurePipTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/test/test_venv.py", line 357, in test_with_pip
    with_pip=True)
subprocess.CalledProcessError: Command '['/tmp/tmp71gop0m5/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/test/test_venv.py", line 363, in test_with_pip
    self.fail(msg.format(exc, details))
AssertionError: Command '['/tmp/tmp71gop0m5/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

**Subprocess Output**
Traceback (most recent call last):
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/ensurepip/__init__.py", line 209, in _main
    default_pip=args.default_pip,
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/ensurepip/__init__.py", line 116, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/ensurepip/__init__.py", line 40, in _run_pip
    import pip
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/log.py", line 9, in <module>
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/__init__.py", line 2, in <module>
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/initialise.py", line 5, in <module>
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/ansitowin32.py", line 6, in <module>
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/winterm.py", line 2, in <module>
  File "/tmp/tmplhy261sg/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/win32.py", line 7, in <module>
  File "/usr/home/db3l/buildarea/3.x.bolen-freebsd7/build/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named '_ctypes'

**Comment by wiggin15** [comment]
Yes, looks like it was fixed - the import is now under try/except which handles ImportError. On Linux, conversion isn't needed so this is ok.
