### ISSUE TITLE
RecursionError exception if init() called multiple times on Win32

### ISSUE THREAD

**Issue by dcleland** [tartley/colorama#182]
colorama 0.3.9
Windows 7 SP1 (64-bit)
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32

If you call init() multiple times you will eventually get a RecursionError exception.

Simple code to reproduce the error. It fails on the 249th iteration

```
#!/usr/bin/python3
from colorama import init
from inspect import getouterframes, currentframe

try:
    for it in range(1, 1001):
        print("Iteration: ", it)
        init()

except Exception:
    one, two, three = sys.exc_info()
    print("{0}\n {1}\n{2}\n".format(one, two, three ))
    

```    
**NOTE**: You will not see the output from the 'except Exception' section, instead you will see

```
  Iteration: Traceback (most recent call last):

  During handling of the above exception, another exception occurred:

```
From a different script that first showed the problem I managed to get the following stack backtrace

```
Iteration: 248
Level is 81,2,3  level  <class 'RecursionError'> === maximum recursion depth exceeded while calling a Python object === <traceback o
bject at 0x0000000003927548> --- 7<----------
Level is 7
Traceback (most recent call last):
  File "W:\XXXXXXXX\test_unsecured_menu_01.py", line 265, in <module>
    test01()
  File "W:\XXXXXXXX\test_unsecured_menu_01.py", line 23, in test01
    print("Level is {}".format( level))   
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])    
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python36_64\lib\site-packages\colorama\ansitowin32.py", line 40, in write
....

```

**Comment by dcleland** [comment]
My sample code is made up of course, but my problem came about because I had multiple instances of a class that used colorama where each instance was doing an init() when was called.

If you don't know a class is using colorama, and you have multiple instances of it or if you have multiple different classes from 3rd parties doing init()/deinit() then things can get confused with respect to the stdout file handles.
