### ISSUE TITLE
Installation failing on Windows - 'No matching distributions found for colorama'

### ISSUE THREAD

**Issue by Guts** [tartley/colorama#223]
I'm using https://github.com/pytest-dev/pytest/ to perform local unit tests and since i made a fresh install on my machine with Windows 10 10.0.17763, I was encountered an issue installing it because of a mismatch of colorama.

FI `pipenv install` is also failing.

**Pip verbose log**

```python
(.venv_pytest) PS C:\Users\$USER\Documents\GitHub\Isogeo\isogeo-api-py-minsdk> python -m pip -v install colorama
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\$USER~1\AppData\Local\Temp\pip-ephem-wheel-cache-imou4kxj
Created temporary directory: C:\Users\$USER~1\AppData\Local\Temp\pip-req-tracker-qjpcmacd
Created requirements tracker 'C:\\Users\\$USER~1\\AppData\\Local\\Temp\\pip-req-tracker-qjpcmacd'
Created temporary directory: C:\Users\$USER~1\AppData\Local\Temp\pip-install-yk0ahksq
Collecting colorama
  1 location(s) to search for versions of colorama:
  * https://pypi.org/simple/colorama/
  Getting page https://pypi.org/simple/colorama/
  Looking up "https://pypi.org/simple/colorama/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/colorama/ HTTP/1.1" 200 7136
  Could not fetch URL https://pypi.org/simple/colorama/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. - skipping
  ERROR: Could not find a version that satisfies the requirement colorama (from versions: none)
Cleaning up...
Removed build tracker 'C:\\Users\\$USER~1\\AppData\\Local\\Temp\\pip-req-tracker-qjpcmacd'
ERROR: No matching distribution found for colorama
Exception information:
Traceback (most recent call last):
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\commands\install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\operations\prepare.py", line 282, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\req\req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\$USER\Documents\GitHub\projects\api\.venv_pytest\lib\site-packages\pip\_internal\index.py", line 792, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for colorama
```

**Workaround**: [download and install  the wheel from PyPi](https://pypi.org/project/colorama/#files).

**Comment by wiggin15** [comment]
```
Could not fetch URL https://pypi.org/simple/colorama/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. - skipping
```
You got a "read timed out" error, i.e. a network failure. Either PyPI was having networking issues at the time you tried to install colorama (you can retry) or there was some other connectivity problem between your machine and PyPI. colorama seems to be correctly available on PyPI, so I don't think there is a problem on our end.

**Comment by Guts** [comment]
I tried a lot along the day and got this error only for this package, so I though that was a specific error...

But indeed our CI installed it then ran the tests without issue. I guess you're right and I can close.
