### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by jiasli** [tartley/colorama#302]
Originally reported at https://github.com/Azure/azure-cli/issues/13413

Colorama fails if output is redirected to `head` command.

test.py:

```py
import sys
from colorama import init, Fore, Style

init()
for i in range(30):
    print(Fore.RED + 'line{}'.format(i) + Style.RESET_ALL)
```

Output:
```
$ python test.py | head --line=1
line0
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(Fore.RED + 'line{}'.format(i) + Style.RESET_ALL)
  File "/home/user1/env-test/lib/python3.8/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/home/user1/env-test/lib/python3.8/site-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/home/user1/env-test/lib/python3.8/site-packages/colorama/ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/home/user1/env-test/lib/python3.8/site-packages/colorama/ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <colorama.ansitowin32.StreamWrapper object at 0x7f5fc3a1efd0>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by tartley** [comment]
https://docs.python.org/3/library/signal.html#note-on-sigpipe

**Comment by njsmith** [comment]
I don't see how this has anything to do with colorama? The exception is being raised by Python itself; colorama only shows up in the traceback because the output is going through it. There's probably some subtle difference in when buffered output gets flushed depending on whether colorama is enabled or not, that happens to tickle the issue in this case, but the underlying issue is independent.

Anyway with the new `just_fix_windows_console` API, colorama won't touch stdout when it's a pipe, so switching to that should take care of this in any case.
