### ISSUE TITLE
ImportError: cannot import name 'init'

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#46]
Migrated from googlecode https://code.google.com/p/colorama/issues/detail?id=66

Reported by Tayyab.Ditta, Yesterday (22 hours ago)
I have installed colorama but i get the following error when running this code:

from colorama import init
from termcolor import colored

# use Colorama to make Termcolor work on Windows too
init()

from colorama import Fore, Back, Style
print(Fore.RED + 'some red text')
print(Back.GREEN + 'and with a green background')
print(Style.DIM + 'and in dim text')
print(Fore.RESET + Back.RESET + Style.RESET_ALL)
print('back to normal now')

I get this error when running the above:

Traceback (most recent call last):
  File "E:/Documents/Python/colorama.py", line 1, in <module>
    from colorama import init
  File "E:/Documents/Python\colorama.py", line 1, in <module>
    from colorama import init
ImportError: cannot import name 'init'

**Comment by wiggin15** [comment]
Looks like you named your file 'colorama.py', so when running `from colorama import init` you're trying to import from your own script. Rename the file to a name that is not reserved by a module.

**Comment by Moridiin03** [comment]
tried it but it prints the following in blue:

[31msome red text
[42mand with a green background
[2mand in dim text
[39m[49m[0m
back to normal now

**Comment by wiggin15** [comment]
So this is a different issue.
I can't reproduce this. Your example works as expected on my computer.
How are you running the script? On what terminal (is it cmd?) Are you sure you are still calling `init()`?

**Comment by Moridiin03** [comment]
Yes im running it on cmd

**Comment by B3nac** [comment]
Just to check every possibility. Your running it on Windows cmd and not Python IDLE right?

**Comment by Moridiin03** [comment]
Yes
On 29 Mar 2015 21:31, "Kyle" <notifications@github.com> wrote:
>
> Just to check every possibility. Your running it on Windows cmd and not
Python IDLE right?

**Comment by msabramo** [comment]
`import colorama; print(colorama)`

**Comment by Moridiin03** [comment]
Yes im running on win 7 and windows cmd

**Comment by B3nac** [comment]
Have you tried all the suggested importing methods?

**Comment by msiemens** [comment]
Just speculating: could this be related to #49?

@Moridiin03 Is the environment variable `TERM` set to a value? In other words, whats the result of running `echo %TERM%` in cmd?

**Comment by tartley** [comment]
The import error seems to be understood to be user error. I'm renaming this ticket to represent the remaining problem.
